reset from prod to stage

diff --git a/.github/workflows/reset.yml b/.github/workflows/reset.yml
--- a/.github/workflows/reset.yml
+++ b/.github/workflows/reset.yml
@@ -3,99 +3,82 @@ name: Reset
 on:
   workflow_call:
     inputs:
-      gke_project_id:
-        description: 'GKE Project ID'
-        required: false
-        type: string
-      gke_cluster:
-        description: 'Cluster name'
-        required: false
-        type: string
-      location:
-        description: 'The location of the GAR'
-        required: false
-        default: us-central1
-        type: string
-      go_version:
-        description: 'Go version'
-        required: false
-        default: 'stable'
-        type: string
-      environment:
-        description: 'Environment'
-        required: false
-        default: dev
-        type: string
       helm_chart_file:
         description: 'Helm Chart'
         required: false
         default: 'deployments/kubernetes/helm/chart'
         type: string
-      version_target:
-        description: 'The makefile target for getting the application version'
-        required: false
-        default: version
-        type: string
     secrets:
-      workload_identity_provider:
-        description: 'Workload Identity Provider'
+      token:
+        description: 'Push Token'
         required: true
-      service_account:
-        description: 'Service Account email address'
-        required: true
-
 jobs:
   # Deploy Branch to Kubernetes Cluster
-  reset-environment:
-    if: inputs.environment != 'dev'
+  rollback:
     runs-on: ubuntu-latest
     steps:
-
-    - name: Checkout Deploy Code
+    - name: Checkout Code
       uses: actions/checkout@v4
-  
-    - name: Setup Go
-      uses: actions/setup-go@v4
       with:
-        go-version: ${{ inputs.go_version }}
-        cache: true
+        ref: stage
+        path: destiny-manifest-stage
+        token: ${{ secrets.token }}
 
-    - name: Echo Input Information
+    - name: Checkout Code
+      uses: actions/checkout@v4
+      with:
+        ref: production
+        path: destiny-manifest-production
+        token: ${{ secrets.token }}
+
+    - name: Preparing to rollback
+      shell: bash
+      env:
+        GH_TOKEN: ${{ secrets.token }}
+      run: |-
+        DIR="destiny-manifest-production"
+
+        if [ ! -d "$DIR" ]; then
+          echo "no production branch found. Can't rollback"
+          exit 1
+        fi
+
+        cd destiny-manifest-production
+        source "build-tags"
+        echo "COMMIT_ID_PRODUCTION=$(echo $COMMIT_ID)" >> $GITHUB_ENV
+
+        cd ../destiny-manifest-staging
+
+        cat <<-EOF > "build-tags"
+        export APP_NAME="$APP_NAME"
+        export IMAGE_TAG="$COMMIT_ID_PRODUCTION"
+        export COMMIT_ID_ROLLBACK=""
+        export COMMIT_ID="$COMMIT_ID_PRODUCTION"
+        export BRANCH="reset"
+        EOF
+
+    - name: Checkout Code
+      uses: actions/checkout@v4
+      with:
+        ref: ${{ env.COMMIT_ID_PRODUCTION }}
+        path: code-source
+        token: ${{ secrets.token }}
+
+    - name: Helming the rollback commit_id code
       shell: bash
       run: |-
-        echo "You are deploying from the ${GITHUB_REF##*/} branch to the ${{ inputs.environment }} environment" 
-    
-    - name: Set branch name
+        cd code-source
+        helm template ${{ inputs.helm_chart_file }} --set app.targetRevision=${{ env.ENV }} --set app.image.pullPolicy=Always --set app.image.tag=${{ env.COMMIT_ID_PRODUCTION }} --set app.version=${{ env.COMMIT_ID_PRODUCTION }} > ../destiny-manifest/manifest/manifest.yaml
+
+    - name: Pushing manifest to ${{ env.ENV }} branch
       shell: bash
+      env:
+        GH_TOKEN: ${{ secrets.token }}
       run: |-
-        echo "CLUSTER_ENV=$(echo ${{ inputs.environment }})" >> $GITHUB_ENV
-        echo "ENV=${GITHUB_REF##*/}" >> $GITHUB_ENV
+        cd destiny-manifest-staging
+        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
+        git config --local user.name "github-actions[bot]"
+        git add .
+        git commit -m "reset ${{ env.ENV }}" --no-verify
+        git push --set-upstream origin ${{ env.ENV }}
 
-    - name: Set Env With Version
-      id: get_version_name
-      shell: bash
-      run: |-
-        echo "VERSION=v$(make ${{ inputs.version_target }})" >> $GITHUB_ENV
-
-    - name: Authenticate to Google Cloud
-      uses: 'google-github-actions/auth@v1'
-      with:
-        workload_identity_provider: ${{ secrets.workload_identity_provider }}
-        service_account: ${{ secrets.service_account }}
-
-    - name: Set up gCloud SDK
-      uses: 'google-github-actions/setup-gcloud@v1'
-      with:
-        project_id: ${{ inputs.repository_project_id }}
-
-    - name: Get the GKE credentials so we can deploy to the cluster
-      uses: google-github-actions/get-gke-credentials@v1.0.2
-      with:
-        cluster_name: ${{ inputs.gke_cluster }}
-        location: ${{ inputs.location }}
-        project_id: ${{ inputs.gke_project_id }}
-
-    - name: Deploy to Kubernetes Cluster
-      shell: bash
-      run: |-
-        helm template ${{ inputs.helm_chart_file }} --set app.targetRevision=${{ env.CLUSTER_ENV }} --set app.image.pullPolicy=Always --set app.image.tag=${{ env.VERSION }} --set app.version=${{ env.VERSION }} | kubectl apply -f -
